# This file shows basic commands that are used when we try to dockerize ur java app !

# Lightweight jdk for building application.
FROM openjdk:17-slim
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

COPY --chown=1001:0 build/libs/some_jar_file.jar/app/

# Create a non-root user for security
RUN addgroup --system appgroup && adduser --system --ingroup appgroup --uid 1001 appuser
USER 1001

#Expose the application port
EXPOSE 8080

#Set the entrypoint
ENTRYPOINT ["java", "-XX:+TieredCompilation", "-Xshare:auto", "-XX:InitialRAMPercentage=50.0", "-XX:MaxRAMPercentage=75.0","-jar","/app/some_jar_file.jar"]